openapi: 3.0.0
info:
  title: SOKO
  description: SOKO-app-API
  version: 0.1.9

servers:
  - url: https://sokoapi-production.up.railway.app/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /users:
    get:
      tags:
        - users
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /register:
    post:
      tags:
        - users
      requestBody:
        description: add new user
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                fullName:
                  type: string
                email:
                  type: string
                password:
                  type: string
                phone:
                  type: string
                allowRules:
                  type: boolean
                accessMail:
                  type: boolean
            example:
              fullName: AniA
              email: avazneli@gmail.com
              password: nikolozi
              phone: "#4257F5"
              allowRules: false
              accessMail: true
      responses:
        "201":
          description: user added
  /login:
    post:
      tags:
        - Auth
      requestBody:
        description: login
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
            example:
              email: avazneli@gmail.com
              password: nikolozi
      responses:
        "200":
          description: user login successfully
