openapi: 3.0.0
info:
  title: SOKO
  description: SOKO-app-API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: production server
  - url: http://localhost:3000/api
    description: local server
paths:
  /users:
    get:
      tags:
        - users
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
